---
name: ci

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      - name: install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: activate devshell
        run: nix develop --impure
      - name: check Python formatting
        run: black --check .
      - name: lint shell scripts
        run: find . -type f -name '*.sh' | xargs shellcheck
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      - name: install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: activate devshell
        run: nix develop --impure
      - name: test
        run: echo TODO && exit 1
...
